docs: add kaplan-meier lesson
Ab2nour/kickstarter-project-analysis pull request #50
Opened 2023-11-14 09:08 UTC by jExbrayat

2023-11-14 13:32 UTC, Ab2nour requested changes
Only nit and typo

2023-11-14 13:32 UTC, Ab2nour commented on src/notebooks/non_parametric_estimation.ipynb
> +    "Soit $\\tau$ une variable aléatoire à valeur dans $\\mathbb{N}^*$ modélisant le jour de succès d'un projet kickstarter.  \n",
nit: Kickstarter

2023-11-14 13:32 UTC, Ab2nour commented on src/notebooks/non_parametric_estimation.ipynb
> +    "On se munit d'un échantillon $\\tau_1,\\dots,\\tau_n$ de variables aléatoires indépendantes indentiquement distribuées suivant la même loi que $\\tau$ et de \n",
typo: identiquement

2023-11-14 13:32 UTC, Ab2nour commented on src/notebooks/non_parametric_estimation.ipynb
> +    "où $d(t)$ est le nombre de succès connues au temps $t$  \n",
typo: connu

2023-12-04 13:14 UTC, jExbrayat commented on src/notebooks/non_parametric_estimation.ipynb
> +    "Soit $\\tau$ une variable aléatoire à valeur dans $\\mathbb{N}^*$ modélisant le jour de succès d'un projet kickstarter.  \n",
done

2023-12-04 13:14 UTC, jExbrayat commented on src/notebooks/non_parametric_estimation.ipynb
> +    "où $d(t)$ est le nombre de succès connues au temps $t$  \n",
done

2024-01-14 23:48 UTC, Ab2nour approved these changes

2024-01-14 23:48 UTC, merged